services:
    app:
        container_name: app
        build:
            context: ./backend
            target: php_dev
        restart: unless-stopped
        volumes:
            - ./backend:/var/www
    web:
        image: nginx:alpine
        container_name: laravel-web
        restart: unless-stopped
        ports:
            - "8080:80" 
        volumes:
            - ./backend:/var/www
            - ./backend/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    db:
        image: mysql:latest
        container_name: laravel-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: pangea
            MYSQL_ROOT_PASSWORD: pangea
            MYSQL_USER: pangea
            MYSQL_PASSWORD: pangea
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
    node:
        build:
            context: ./frontend
            target: node_dev
            args:
                USER_ID: ${USER_ID:-1000}
                GROUP_ID: ${GROUP_ID:-1000}
        ports:
            - ${NODE_PORT:-4200}:4200
        volumes:
            - ./frontend:/app
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
volumes:
    dbdata:

